# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: 'Next.js Bundle Analysis'

on:
  pull_request:
  push:
    branches:
      - canary
      - MERL-372-track-package-sizes
  workflow_dispatch:

defaults:
  run:
    working-directory: ./examples/next/faustwp-getting-started

permissions:
  contents: read # for checkout repository
  actions: read # for fetching base branch bundle stats
  pull-requests: write # for comments

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./examples/next/faustwp-getting-started
          useLockFile: false

      - name: Restore next build
        uses: actions/cache@v3
        id: restore-build-cache
        env:
          cache-name: cache-next-build
        with:
          # if you use a custom build directory, replace all instances of `.next` in this file with your build directory
          # ex: if your app builds to `dist`, replace `.next` with `dist`
          path: .next/cache
          # change this if you prefer a more strict cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Build next.js app
        working-directory: ./examples/next/faustwp-getting-started
        run: |
          rm ../../../package.json
          rm ../../../package-lock.json
          cp .env.local.sample .env.local
          npm install @next/bundle-analyzer
          npm run build

      # Here's the first place where next-bundle-analysis' own script is used
      # This step pulls the raw bundle stats for the current bundle
      - name: Analyze bundle
        working-directory: ./examples/next/faustwp-getting-started
        run: npx -p nextjs-bundle-analysis report

      - name: Upload bundle
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: ./examples/next/faustwp-getting-started/.next/analyze/__bundle_analysis.json

      - uses: actions/download-artifact@v3
        if: success() && github.event.number
        with:
          name: bundle
          path: ./examples/next/faustwp-getting-started/.next/analyze/base

      - name: Display structure of downloaded files
        working-directory: ./examples/next/faustwp-getting-started
        run: ls -Ra .next/

      - name: Compare with base branch bundle
        if: success() && github.event.number
        working-directory: ./examples/next/faustwp-getting-started
        run: |
          ls -laR .next/analyze/base
          mkdir -p .next/analyze/base/bundle
          mv .next/analyze/base/* .next/analyze/base/bundle
          npx -p nextjs-bundle-analysis compare

      - name: Get Comment Body
        id: get-comment-body
        if: success() && github.event.number
        working-directory: ./examples/next/faustwp-getting-started
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        run: |
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat .next/analyze/__bundle_analysis_comment.txt)" >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        if: success() && github.event.number
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: '<!-- __NEXTJS_BUNDLE -->'

      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v2
        if: success() && github.event.number && steps.fc.outputs.comment-id == 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}

      - name: Update Comment
        uses: peter-evans/create-or-update-comment@v2
        if: success() && github.event.number && steps.fc.outputs.comment-id != 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
